# Copyright 2024 METRO Digital GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: pre-commit

on:  # yamllint disable-line rule:truthy
  pull_request:

permissions:
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install terraform-docs
        run: |
          curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest |
            grep -o -E -m 1 "https://.+?-linux-amd64.tar.gz")" > terraform-docs.tgz && \
            tar -xzf terraform-docs.tgz terraform-docs && rm terraform-docs.tgz && chmod +x terraform-docs && \
            sudo mv terraform-docs /usr/bin/
      - name: Install tflint
        run: |
          # tflint
          curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest |
            grep -o -E -m 1 "https://.+?_linux_amd64.zip")" > tflint.zip && \
            unzip tflint.zip && rm tflint.zip && sudo mv tflint /usr/bin/
      - name: Install shfmt
        run: |
          curl -L "$(curl -s https://api.github.com/repos/mvdan/sh/releases/latest |
            grep -o -E -m 1 "https://.+?_linux_amd64")" > shfmt && \
            chmod +x shfmt && sudo mv shfmt /usr/bin/

      - name: pre-commit
        uses: pre-commit/action@v3.0.0
